server:
  port: 9080
  compression:
    enabled: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  server:
    port: 9081
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full

# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
spring:
  jpa:
    open-in-view: false
#    hibernate:
#      naming:
#        physical-strategy: com.soebes.spring.example.MappingNames
#      ddl-auto: validate
    show-sql: true
  application:
    name: ThisIsTheFirst
    admin:
      enabled: true
  main:
    banner-mode: console
  banner:
    location: classpath:/banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: dbuser
    password: mysecretpassword
  flyway:
    clean-disabled: true
    create-schemas: true
    enabled: true

#management.endpoints.web.exposure.include=openapi, swagger-ui